package com.match.SwipeAI.dto;

import com.match.SwipeAI.enums.MatchStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

/**
 * Data Transfer Objects for Matches, Pre-Chat Icebreaker Games, and AI Wingman Sparks.
 */
public class MatchDto {

    /**
     * Active match card response.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class MatchResponseDto {
        private UUID id;
        private UUID otherUserId;
        private String otherUserName;
        private String otherUserPhoto;
        private int otherUserAge;
        private boolean isDigilockerVerified;
        private MatchStatus status;
        private Integer messagesCount;
        private long remainingHours;
        private OffsetDateTime expiresAt;
        private OffsetDateTime matchedAt;
        private IcebreakerQuizDto icebreakerQuiz;
        private String lastMessage;
        private OffsetDateTime lastMessageTime;
    }

    /**
     * 10-second rapid-fire icebreaker quiz data.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class IcebreakerQuizDto {
        private String quizId;
        private String title;
        private String question;
        private List<String> options;
        private Integer userAAnswer;
        private Integer userBAnswer;
        private boolean isCompleted;
        private boolean isMutualAgreement;
        private String wingmanRecommendation;
    }

    /**
     * User's selected option in the icebreaker quiz.
     */
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class IcebreakerAnswerRequest {
        private int selectedOptionIndex;
    }

    /**
     * Result after answering icebreaker quiz, including AI Wingman conversation suggestions.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class IcebreakerAnswerResponse {
        private boolean isQuizCompleted;
        private boolean isMutualAgreement;
        private MatchStatus newMatchStatus;
        private IcebreakerQuizDto quizState;
        private List<String> wingmanSparks;
        private String message;
    }

    /**
     * Contextual conversational sparks generated by AI Wingman.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class WingmanSparksResponse {
        private UUID matchId;
        private String candidateName;
        private List<String> sparks;
        private String commonGround;
    }
}
