package com.match.SwipeAI.init;

import com.match.SwipeAI.model.MicroCommunity;
import com.match.SwipeAI.repository.MicroCommunityRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.util.List;

@Slf4j
@Component
@Order(10)
@RequiredArgsConstructor
public class MicroCommunityInitializer implements CommandLineRunner {

    private final MicroCommunityRepository repository;

    @Override
    public void run(String... args) {
        log.info("Checking and seeding Indian Urban Micro-Communities across Bengaluru, Mumbai, Delhi NCR, Gurgaon, Pune, Hyderabad, Goa, Kolkata & Chennai...");

        List<MicroCommunity> communities = List.of(
            // BENGALURU
            MicroCommunity.builder()
                .city("Bengaluru")
                .name("Koramangala Tech Founders")
                .slug("blr-koramangala")
                .tagline("Early-stage founders, product designers & VC analysts")
                .vibeCategory("STARTUP")
                .badgeIcon("🚀")
                .iconName("laptop-outline")
                .centerLat(12.9352)
                .centerLng(77.6245)
                .activeMembersCount(1420)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Bengaluru")
                .name("Indiranagar Cafe Hoppers")
                .slug("blr-indiranagar")
                .tagline("Aesthetic cafes, craft microbreweries, designers & indie gigs")
                .vibeCategory("CREATIVE")
                .badgeIcon("🎨")
                .iconName("color-palette-outline")
                .centerLat(12.9784)
                .centerLng(77.6408)
                .activeMembersCount(1850)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Bengaluru")
                .name("HSR Unicorn Coders")
                .slug("blr-hsr-layout")
                .tagline("Unicorn engineers, Cult.fit regulars & AI builders")
                .vibeCategory("TECH")
                .badgeIcon("⚡")
                .iconName("flash-outline")
                .centerLat(12.9121)
                .centerLng(77.6446)
                .activeMembersCount(1260)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Bengaluru")
                .name("Whitefield Corporate Tech")
                .slug("blr-whitefield")
                .tagline("Suburban tech corridor, corporate leaders & expats")
                .vibeCategory("CORPORATE")
                .badgeIcon("💼")
                .iconName("briefcase-outline")
                .centerLat(12.9698)
                .centerLng(77.7500)
                .activeMembersCount(940)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Bengaluru")
                .name("Church Street Book Lovers")
                .slug("blr-church-street")
                .tagline("Blossom bookstore dates, art galleries & vintage Bangalore charm")
                .vibeCategory("CULTURE")
                .badgeIcon("📚")
                .iconName("book-outline")
                .centerLat(12.9749)
                .centerLng(77.6092)
                .activeMembersCount(1120)
                .isPopular(false)
                .build(),
            MicroCommunity.builder()
                .city("Bengaluru")
                .name("JP Nagar Filter Coffee & Arts")
                .slug("blr-jp-nagar")
                .tagline("South Bangalore nostalgia, theater artists, filter coffee & Ranga Shankara")
                .vibeCategory("HERITAGE")
                .badgeIcon("☕")
                .iconName("cafe-outline")
                .centerLat(12.9063)
                .centerLng(77.5857)
                .activeMembersCount(880)
                .isPopular(false)
                .build(),
            MicroCommunity.builder()
                .city("Bengaluru")
                .name("Bellandur & ORR Hackers")
                .slug("blr-bellandur")
                .tagline("High-growth tech parks, late-night hackathons & fitness buffs")
                .vibeCategory("TECH")
                .badgeIcon("💻")
                .iconName("code-slash-outline")
                .centerLat(12.9260)
                .centerLng(77.6762)
                .activeMembersCount(750)
                .isPopular(false)
                .build(),

            // MUMBAI
            MicroCommunity.builder()
                .city("Mumbai")
                .name("Bandra West Creatives")
                .slug("mum-bandra-west")
                .tagline("Pali Hill creatives, seaside runners, third-wave coffee & Bollywood media")
                .vibeCategory("CREATIVE")
                .badgeIcon("🎬")
                .iconName("videocam-outline")
                .centerLat(19.0596)
                .centerLng(72.8295)
                .activeMembersCount(2350)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Mumbai")
                .name("Lower Parel High-Finance")
                .slug("mum-lower-parel")
                .tagline("Investment bankers, corporate lawyers, luxury rooftop nightlife & Kamala Mills")
                .vibeCategory("CORPORATE")
                .badgeIcon("🍸")
                .iconName("wine-outline")
                .centerLat(18.9986)
                .centerLng(72.8311)
                .activeMembersCount(1680)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Mumbai")
                .name("Versova Indie Cinema & Theater")
                .slug("mum-versova")
                .tagline("Writers, indie cinema actors, theater directors & seaside sunset chai")
                .vibeCategory("ART")
                .badgeIcon("🎭")
                .iconName("ticket-outline")
                .centerLat(19.1351)
                .centerLng(72.8146)
                .activeMembersCount(1420)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Mumbai")
                .name("Powai Lake Tech Tribe")
                .slug("mum-powai")
                .tagline("IIT Bombay grads, fintech founders & lakeside chill")
                .vibeCategory("STARTUP")
                .badgeIcon("🌊")
                .iconName("water-outline")
                .centerLat(19.1176)
                .centerLng(72.9060)
                .activeMembersCount(1190)
                .isPopular(false)
                .build(),
            MicroCommunity.builder()
                .city("Mumbai")
                .name("Juhu Beachside Brunches")
                .slug("mum-juhu")
                .tagline("Aesthetic weekend brunches, fitness enthusiasts & film industry circles")
                .vibeCategory("LIFESTYLE")
                .badgeIcon("🌴")
                .iconName("sunny-outline")
                .centerLat(19.0988)
                .centerLng(72.8264)
                .activeMembersCount(1530)
                .isPopular(false)
                .build(),
            MicroCommunity.builder()
                .city("Mumbai")
                .name("Colaba & SoBo Heritage")
                .slug("mum-colaba-sobo")
                .tagline("Kala Ghoda art galleries, colonial heritage walks & jazz bistros")
                .vibeCategory("HERITAGE")
                .badgeIcon("🏛️")
                .iconName("business-outline")
                .centerLat(18.9067)
                .centerLng(72.8147)
                .activeMembersCount(980)
                .isPopular(false)
                .build(),

            // DELHI NCR
            MicroCommunity.builder()
                .city("Delhi NCR")
                .name("Hauz Khas Bohemian Artists")
                .slug("del-hauz-khas")
                .tagline("Bohemian artists, indie musicians & heritage lake ruins cafes")
                .vibeCategory("CREATIVE")
                .badgeIcon("🎸")
                .iconName("musical-notes-outline")
                .centerLat(28.5535)
                .centerLng(77.2023)
                .activeMembersCount(2140)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Delhi NCR")
                .name("Cyber City & Golf Course Leaders")
                .slug("del-cyber-city")
                .tagline("Consultants (McKinsey/BCG), Fortune 500 execs & microbrewery culture")
                .vibeCategory("CORPORATE")
                .badgeIcon("🏙️")
                .iconName("business-outline")
                .centerLat(28.4950)
                .centerLng(77.0895)
                .activeMembersCount(1890)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Delhi NCR")
                .name("North Campus DU Adda")
                .slug("del-north-campus")
                .tagline("Delhi University collegiate pulse, street food, debates & Hudson Lane")
                .vibeCategory("COLLEGIATE")
                .badgeIcon("🎓")
                .iconName("school-outline")
                .centerLat(28.6896)
                .centerLng(77.2105)
                .activeMembersCount(3100)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Delhi NCR")
                .name("Greater Kailash South Delhi Chic")
                .slug("del-gk-south-delhi")
                .tagline("South Delhi chic, high-street fashion & boutique Italian bistros")
                .vibeCategory("LIFESTYLE")
                .badgeIcon("✨")
                .iconName("sparkles-outline")
                .centerLat(28.5380)
                .centerLng(77.2435)
                .activeMembersCount(1720)
                .isPopular(false)
                .build(),
            MicroCommunity.builder()
                .city("Delhi NCR")
                .name("Noida Sector 18 Media & Tech")
                .slug("del-noida-sector-18")
                .tagline("News media anchors, tech park professionals & mall hangouts")
                .vibeCategory("MEDIA")
                .badgeIcon("📺")
                .iconName("tv-outline")
                .centerLat(28.5708)
                .centerLng(77.3260)
                .activeMembersCount(1280)
                .isPopular(false)
                .build(),

            // PUNE
            MicroCommunity.builder()
                .city("Pune")
                .name("Koregaon Park (KP) Bohemians")
                .slug("pun-koregaon-park")
                .tagline("Osho heritage, European cafes, international students & nightlife")
                .vibeCategory("BOHEMIAN")
                .badgeIcon("🌿")
                .iconName("leaf-outline")
                .centerLat(18.5362)
                .centerLng(73.8940)
                .activeMembersCount(1650)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Pune")
                .name("Viman Nagar Symbiosis Tribe")
                .slug("pun-viman-nagar")
                .tagline("Symbiosis student pulse, young IT recruits & bustling food streets")
                .vibeCategory("COLLEGIATE")
                .badgeIcon("🎒")
                .iconName("people-outline")
                .centerLat(18.5679)
                .centerLng(73.9143)
                .activeMembersCount(1920)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Pune")
                .name("Balewadi High Street & Baner")
                .slug("pun-balewadi-high-st")
                .tagline("Hinjewadi tech crowd, sports enthusiasts & modern pubs")
                .vibeCategory("TECH")
                .badgeIcon("⚽")
                .iconName("football-outline")
                .centerLat(18.5750)
                .centerLng(73.7740)
                .activeMembersCount(1140)
                .isPopular(false)
                .build(),
            MicroCommunity.builder()
                .city("Pune")
                .name("FC Road & Deccan Adda")
                .slug("pun-fc-road")
                .tagline("Historic Fergusson adda, Vaishali/Goodluck dates & cultural nostalgia")
                .vibeCategory("HERITAGE")
                .badgeIcon("☕")
                .iconName("cafe-outline")
                .centerLat(18.5236)
                .centerLng(73.8415)
                .activeMembersCount(1380)
                .isPopular(false)
                .build(),

            // HYDERABAD
            MicroCommunity.builder()
                .city("Hyderabad")
                .name("Jubilee Hills Luxury & Lounges")
                .slug("hyd-jubilee-hills")
                .tagline("Tollywood creatives, entrepreneurs, luxury lounges & scenic hill drives")
                .vibeCategory("LUXURY")
                .badgeIcon("👑")
                .iconName("diamond-outline")
                .centerLat(17.4319)
                .centerLng(78.4073)
                .activeMembersCount(1590)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Hyderabad")
                .name("Hitec City & Madhapur Cyberabad")
                .slug("hyd-hitec-city")
                .tagline("Cyberabad techies, late-night drive-ins & MNC consultants")
                .vibeCategory("TECH")
                .badgeIcon("🌐")
                .iconName("globe-outline")
                .centerLat(17.4474)
                .centerLng(78.3762)
                .activeMembersCount(2180)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Hyderabad")
                .name("Gachibowli Financial District")
                .slug("hyd-gachibowli")
                .tagline("Amazon/Google/Microsoft towers, sports stadium runs & township living")
                .vibeCategory("CORPORATE")
                .badgeIcon("🏢")
                .iconName("fitness-outline")
                .centerLat(17.4401)
                .centerLng(78.3489)
                .activeMembersCount(1370)
                .isPopular(false)
                .build(),

            // GOA
            MicroCommunity.builder()
                .city("Goa")
                .name("Anjuna & Assagao Nomads")
                .slug("goa-anjuna-assagao")
                .tagline("Digital nomads, wellness instructors, sunset acoustic dates & slow living")
                .vibeCategory("NOMAD")
                .badgeIcon("🧘")
                .iconName("flower-outline")
                .centerLat(15.5871)
                .centerLng(73.7423)
                .activeMembersCount(980)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Goa")
                .name("Panjim & Fontainhas Latin Quarter")
                .slug("goa-panjim")
                .tagline("Latin quarter walks, heritage Portuguese cafes & indie art curators")
                .vibeCategory("HERITAGE")
                .badgeIcon("🏘️")
                .iconName("home-outline")
                .centerLat(15.4909)
                .centerLng(73.8278)
                .activeMembersCount(640)
                .isPopular(false)
                .build(),

            // KOLKATA
            MicroCommunity.builder()
                .city("Kolkata")
                .name("Park Street Jazz & Heritage")
                .slug("kol-park-street")
                .tagline("Vintage jazz, iconic tearooms, nightlife & colonial charm")
                .vibeCategory("HERITAGE")
                .badgeIcon("🎷")
                .iconName("musical-notes-outline")
                .centerLat(22.5535)
                .centerLng(88.3512)
                .activeMembersCount(1240)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Kolkata")
                .name("Salt Lake & Sector V IT")
                .slug("kol-salt-lake")
                .tagline("IT engineers, startup builders, modern cafes & lakeside hangouts")
                .vibeCategory("TECH")
                .badgeIcon("💡")
                .iconName("bulb-outline")
                .centerLat(22.5735)
                .centerLng(88.4331)
                .activeMembersCount(1460)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Kolkata")
                .name("Southern Avenue Intellectual Adda")
                .slug("kol-south-kolkata")
                .tagline("Intellectual adda, lake walks, poetry, art galleries & classical culture")
                .vibeCategory("CULTURE")
                .badgeIcon("📖")
                .iconName("book-outline")
                .centerLat(22.5126)
                .centerLng(88.3582)
                .activeMembersCount(1150)
                .isPopular(false)
                .build(),

            // CHENNAI
            MicroCommunity.builder()
                .city("Chennai")
                .name("Besant Nagar (Bessie Beach)")
                .slug("che-besant-nagar")
                .tagline("Early morning beach runners, seaside cafes & bohemian creatives")
                .vibeCategory("COASTAL")
                .badgeIcon("🌊")
                .iconName("water-outline")
                .centerLat(13.0003)
                .centerLng(80.2667)
                .activeMembersCount(1020)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Chennai")
                .name("Nungambakkam & Alwarpet Culture")
                .slug("che-nungambakkam")
                .tagline("Classical music sabhas meet modern bistros, diplomatic clubs & indie arts")
                .vibeCategory("CULTURE")
                .badgeIcon("🎻")
                .iconName("color-palette-outline")
                .centerLat(13.0569)
                .centerLng(80.2425)
                .activeMembersCount(870)
                .isPopular(true)
                .build(),

            // GURGAON (GURUGRAM)
            MicroCommunity.builder()
                .city("Gurgaon")
                .name("Cyber Hub & DLF Phase 2")
                .slug("ggn-cyber-hub")
                .tagline("Fortune 500 consultants, MNC tech leads, rooftop beers & post-work networking")
                .vibeCategory("CORPORATE")
                .badgeIcon("🏙️")
                .iconName("business-outline")
                .centerLat(28.4950)
                .centerLng(77.0895)
                .activeMembersCount(2450)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Gurgaon")
                .name("Golf Course Road & Horizon Luxe")
                .slug("ggn-golf-course-rd")
                .tagline("Private equity, luxury high-rises, artisanal matcha & weekend golfers")
                .vibeCategory("LUXURY")
                .badgeIcon("⛳")
                .iconName("trophy-outline")
                .centerLat(28.4680)
                .centerLng(77.0980)
                .activeMembersCount(1980)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Gurgaon")
                .name("32nd Avenue Aesthetic Dates")
                .slug("ggn-32nd-avenue")
                .tagline("Cobblestone alleys, jazz evenings at Piano Man, boutique gelato & curated date nights")
                .vibeCategory("ROMANTIC")
                .badgeIcon("🍷")
                .iconName("sparkles-outline")
                .centerLat(28.4611)
                .centerLng(77.0514)
                .activeMembersCount(2150)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Gurgaon")
                .name("Sector 29 Craft Beer & Live Gigs")
                .slug("ggn-sector-29")
                .tagline("Microbrewery hopping, fresh wheat beer on tap, live Bollywood rock & weekend party animals")
                .vibeCategory("NIGHTLIFE")
                .badgeIcon("🍻")
                .iconName("beer-outline")
                .centerLat(28.4682)
                .centerLng(77.0628)
                .activeMembersCount(2800)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Gurgaon")
                .name("Galleria Market & Phase 4 Chills")
                .slug("ggn-galleria-market")
                .tagline("Fountain steps banter, third-wave coffee, dog parents & nostalgic DLF community vibes")
                .vibeCategory("LIFESTYLE")
                .badgeIcon("☕")
                .iconName("cafe-outline")
                .centerLat(28.4674)
                .centerLng(77.0818)
                .activeMembersCount(1760)
                .isPopular(true)
                .build(),
            MicroCommunity.builder()
                .city("Gurgaon")
                .name("Golf Course Ext & Sohna Rd Startups")
                .slug("ggn-gcr-ext-startups")
                .tagline("Fintech founders, modern gated societies, Cult.fit regulars & weekend pickleball")
                .vibeCategory("STARTUP")
                .badgeIcon("🚀")
                .iconName("rocket-outline")
                .centerLat(28.4180)
                .centerLng(77.0650)
                .activeMembersCount(1340)
                .isPopular(false)
                .build(),
            MicroCommunity.builder()
                .city("Gurgaon")
                .name("Aravali Trails & Sunset Riders")
                .slug("ggn-aravali-biodiversity")
                .tagline("Sunrise gravel cycling, Leopard Trail chai, marathon training & nature lovers")
                .vibeCategory("FITNESS")
                .badgeIcon("🚴")
                .iconName("bicycle-outline")
                .centerLat(28.4350)
                .centerLng(77.0180)
                .activeMembersCount(1120)
                .isPopular(false)
                .build()
        );

        int added = 0;
        for (MicroCommunity comm : communities) {
            if (repository.findBySlug(comm.getSlug()).isEmpty()) {
                repository.save(comm);
                added++;
            }
        }
        if (added > 0) {
            log.info("Successfully added {} new micro-communities. Total now in DB: {}.", added, repository.count());
        } else {
            log.info("All {} micro-communities already up to date.", repository.count());
        }
    }
}
